### ISSUE TITLE
⚡️[FEAT] 아르키 main page 제작

### ISSUE THREAD

**Issue by racheliee** [archi-corp/about-us#4]
# 아르키 main 페이지 제작

해당 issue에 맞는 branch로 작업하고 merge 해주시길 바랍니다! 🙇🏻‍♀️

## 🎨 design
- app 배포 기반으로 디자인 구상하시면 될것 같습니다

## 👾 포함되어야할 내용:
- 해당 내용은 자유롭게 수정 가능합니다!
- [x] 앱 사진 (모델, 화면 등등)
- [ ] 앱 다운로드/보기 링크 혹은 버튼
- [x] 서비스 소개
- [ ] 슬로건

**Comment by elect10** [comment]
다운로드 링크 ,슬로건 등은 존재하지 않는 이유로..,,, 좀더 고민후 추후 추가 하겠습니다.,
